# Generated by Django 3.1.2 on 2020-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fech_corta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.DateField(blank=True, verbose_name='lote')),
                ('codigo', models.IntegerField(blank=True, verbose_name='codigo')),
                ('producto', models.TextField(blank=True, max_length=20, verbose_name='producto')),
                ('vencimiento', models.DateField(blank=True, verbose_name='vencimiento')),
                ('vida', models.IntegerField(blank=True, verbose_name='vida')),
                ('cantidad', models.FloatField(blank=True, verbose_name='cantidad')),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrase',
            field=models.TextField(max_length=10, verbose_name='contraseña'),
        ),
    ]
