# Generated by Django 3.1.2 on 2020-11-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinaApp', '0002_auto_20201101_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fech_corta',
            name='lote',
            field=models.DateField(blank=True, null=True, verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='fech_corta',
            name='vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='vencimiento'),
        ),
    ]
