# Generated by Django 3.1.2 on 2020-11-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinaApp', '0003_auto_20201104_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='donaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.DateField(blank=True, null=True, verbose_name='lote')),
                ('codigo', models.IntegerField(blank=True, verbose_name='codigo')),
                ('producto', models.TextField(blank=True, max_length=20, verbose_name='producto')),
                ('vencimiento', models.DateField(blank=True, null=True, verbose_name='vencimiento')),
                ('vida', models.IntegerField(blank=True, verbose_name='vida')),
                ('cantidad', models.FloatField(blank=True, verbose_name='cantidad')),
            ],
        ),
    ]
