# Generated by Django 3.1.2 on 2020-11-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpinaApp', '0004_donaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donaciones',
            name='vencimiento',
        ),
    ]
